name: Pull upstream changes from the `raycast/extensions` repo

on:
  schedule:
    # This workflow will automatically run at 5am once per week (Monday)...
    - cron: "0 5 * * 1"
  # ...and you can also trigger it manually from GitHub's UI.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: timrogers/pull-raycast-extension-changes@v1.0.0
        with:
          # CHANGE ME to the name of your extension. This should be the name of the folder in `raycast/extensions`, under `extensions/`, where your extension lives.
          extension_name: markdown-preview
          # Leave this as it is. It'll automatically use the GitHub token provided by the GitHub Actions runtime.
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
